dist: trusty
language: node_js
node_js:
  - 6
cache:
  directories:
  - node_modules
notifications:
  slack:
    on_success: always
    rooms:
      - lumas:O4OT9JDz0oR0zchHEyasTVbp#general
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8    